server:
  port: 8080

spring:
  datasource:
    name:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://162.14.64.229:3306/feiyang?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB