package com.example.newcodercommunity.mapper;

import com.example.newcodercommunity.entity.DiscussPost;
import com.example.newcodercommunity.entity.DiscussPostExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface DiscussPostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated
     */
    long countByExample(DiscussPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated
     */
    int deleteByExample(DiscussPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated
     */
    int insert(DiscussPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated
     */
    int insertSelective(DiscussPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated
     */
    List<DiscussPost> selectByExampleWithBLOBs(DiscussPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated
     */
    List<DiscussPost> selectByExample(DiscussPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated
     */
    DiscussPost selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DiscussPost record, @Param("example") DiscussPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") DiscussPost record, @Param("example") DiscussPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DiscussPost record, @Param("example") DiscussPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DiscussPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(DiscussPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DiscussPost record);
}